### PR TITLE
Dynamically loaded phrases/words and optimized handling.

### PR DESCRIPTION
**Pull request by Shilo**
I understand if you don't want to merge this, it's quite a rework. Wont hurt my feelings if you decline it.

Changes:
- Phrases/Words are loaded from `data/phrases.txt` and `data/words.txt`
- Added test function.
- Optimized and simplified parsing of phrases so that it's not hardcoded.
- Added a few extra phrases and words.
- I tested locally and there should be no bugs, but your setup will rely on file loading for `data/phrases.txt` and `data/words.txt`.

You can test it by `running in an IDE such as PyCharm` or by calling `test_translate()` at the end of `main.py`. Test will output 10 phrases in a row.
Example:
```
main.py::test_translate PASSED                                           [100%]
A day dream is a penny towards a penny.
Better a small penny than an empty earned.
A penniless penny is pennied and penny apple.
A walked penny is day and say penny.
A apple penny is penny and given lost.
A wise pretty penny is a wise eaten gained.
A wise given penniless is a wise pretty penny.
You know what they say, a pennied penny is a day say.
You know what they say, a apple given is a penny eaten.
Better a small day than an empty penny.
```

### CODE REVIEW

**Comment by Shilo** [comment]
I just realised there is a merge conflict, but my fork was in-sync with latest commit so im confused. I will look at conflicts.

**Comment by Shilo** [comment]
Fixed unknown conflict, the problem was Git.

**Comment by Shilo** [comment]
Just realised previous version does:
- Minimum of 1 "penny", any order.

My version:
- "penny" always first word.

I will need to fix the design to be the same.
- shuffle words
- allow x minimum times of "penny".

**Comment by Shilo** [comment]
Fixed design to be same as previous.

**Review by code807 — CHANGES_REQUESTED** [review]
`test_translate` function should probably be removed. `fixed_words_left` should be renamed `fixed_words_remaining`. Otherwise this looks great, will merge after those changes.

**Comment by Shilo** [comment]
Made the requested changes. You know what they say: `Better a small real than an empty penny.`

**Review by code807 — APPROVED** [review]

**Pull request merged**
